#!/usr/bin/env python3
"""Generate a C++ translation unit that force-instantiates the top concrete
template instantiations mined by mine_instantiations.py, so their layouts
can actually be dumped and checked (neither libclang nor CastXML expands
templates on their own -- see DESIGN.md's "Base tooling" section).

Emits `using _force_N = Template<Args>;` aliases plus a `sizeof` reference
for each (forces the compiler to instantiate and complete the type) rather
than explicit `template class Template<Args>;` instantiation, because the
latter fails outright for types with deleted/private members in some
CommonLibSSE-NG templates -- a `using` alias plus `sizeof` only requires
the type to be *completable*, not explicitly instantiable as a standalone
translation unit, which is a strictly weaker (and here, sufficient)
requirement for a layout-only pass.

Usage:
    python3 generate_forced_instantiations.py <CommonLibSSE-NG>/include \
        --template BSTArray --top 5 > /tmp/forced.cpp
    # then feed /tmp/forced.cpp's #include line + contents into dump_layout.sh,
    # or just cat it after a #include "RE/Skyrim.h"-equivalent umbrella.
"""
import argparse
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).parent))
import mine_instantiations  # noqa: E402
from mine_instantiations import mine_template, DEFAULT_TEMPLATES  # noqa: E402
from collections import Counter


def qualify(template_name: str) -> str:
    """CommonLibSSE-NG templates live in RE:: unless already qualified
    (REL::Relocation, stl::enumeration already carry their namespace)."""
    if "::" in template_name:
        return template_name
    return f"RE::{template_name}"


def main():
    parser = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    parser.add_argument("include_dir", type=Path)
    parser.add_argument("--template", action="append", dest="templates")
    parser.add_argument("--top", type=int, default=5)
    parser.add_argument("--header", default="RE/T/TESForm.h",
                         help="Header to #include first, providing the types referenced in instantiations")
    args = parser.parse_args()

    templates = args.templates or DEFAULT_TEMPLATES
    re_dir = args.include_dir / "RE"

    counters = {name: Counter() for name in templates}
    nested = Counter()
    mine_instantiations.ALL_TEMPLATE_NAMES = templates

    for path in re_dir.rglob("*.h"):
        text = path.read_text(errors="ignore")
        for name in templates:
            mine_template(text, name, counters[name], nested)

    print(f'#include "{args.header}"')
    print()
    print("// GENERATED by generate_forced_instantiations.py -- force-instantiate")
    print("// the top concrete template usages so their layouts can be dumped.")
    print("namespace gcpp_forced_instantiation {")
    print("    using namespace RE;  // instantiation args are often unqualified RE:: type names")

    idx = 0
    for name in templates:
        for instantiation, count in counters[name].most_common(args.top):
            full = qualify(instantiation)
            print(f"    // {count} occurrences: {full}")
            print(f"    using _force_{idx} = {full};")
            print(f"    constexpr auto _size_{idx} = sizeof(_force_{idx});")
            idx += 1

    print("}")


if __name__ == "__main__":
    main()
